---
version: "3.8"
services:
  postgres:
    image: "postgres:14-alpine"
    env_file:
      - "development.env"
      - "creds.env"
    volumes:
      # - "./nautobot.sql:/tmp/nautobot.sql"
      - "postgres_data:/var/lib/postgresql/data"
  redis:
    image: "redis:6-alpine"
    command:
      - "sh"
      - "-c"  # this is to evaluate the $NAUTOBOT_REDIS_PASSWORD from the env
      - "redis-server --appendonly yes --requirepass $$NAUTOBOT_REDIS_PASSWORD"
    env_file:
      - "development.env"
      - "creds.env"
volumes:
  postgres_data: {}
